### ISSUE TITLE
No MD5 fingerprint found error when upgrade from 4.18 to 4.19

### ISSUE THREAD

**Issue by Jack-Hua-Lu** [calabash/calabash-android#351]
Everything works fine on v4.18. After I update calabash-android to v4.19. Following errors were thrown when trying to run script:
:\Users\JLu\Documents\backupFromJackDT\Jack\workspace\workspace\calabash\calaba
sh-android-demoapp-master\calabash>calabash-android console Asgl.Android-Signed_
QA1_Debug-resigned.apk
No test server found for this combination of app and calabash version. Recreatin
g test server.
Exception in thread "main" java.lang.NoClassDefFoundError: '-Dfile/encoding=utf-
8'
Caused by: java.lang.ClassNotFoundException: '-Dfile.encoding=utf-8'
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: '-Dfile.encoding=utf-8'.  Program will exit.
C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.19/lib/calabash-android
/helpers.rb:106:in `extract_md5_fingerprint': No MD5 fingerprint found: (Runtime
Error)

```
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.19/lib/cal
```

abash-android/helpers.rb:97:in `block (2 levels) in fingerprint_from_apk'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.19/lib/cal
abash-android/helpers.rb:83:in`chdir'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.19/lib/cal
abash-android/helpers.rb:83:in `block in fingerprint_from_apk'
        from C:/Ruby193/lib/ruby/1.9.1/tmpdir.rb:83:in`mktmpdir'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.19/lib/cal
abash-android/helpers.rb:82:in `fingerprint_from_apk'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.19/bin/cal
abash-android-build.rb:2:in`calabash_build'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.19/lib/cal
abash-android/helpers.rb:45:in `build_test_server_if_needed'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.19/bin/cal
abash-android-console.rb:18:in`calabash_console'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/calabash-android-0.4.19/bin/cal
abash-android:85:in `<top (required)>'
        from C:/Ruby193/bin/calabash-android:23:in`load'
        from C:/Ruby193/bin/calabash-android:23:in `<main>'
